"""add care plan to CarOwnership

Revision ID: 026ea788d410
Revises: ce2520ee6e50
Create Date: 2026-05-17 12:34:20.648386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026ea788d410'
down_revision = 'ce2520ee6e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_ownership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('care_plan', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_ownership', schema=None) as batch_op:
        batch_op.drop_column('care_plan')

    # ### end Alembic commands ###
