"""add BookingIntent to database

Revision ID: 036d7fd633b4
Revises: 4ea36e64289c
Create Date: 2026-04-14 20:37:48.234440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036d7fd633b4'
down_revision = '4ea36e64289c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_intent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_intent')
    # ### end Alembic commands ###
