"""modify access code

Revision ID: 0642a7f8ed12
Revises: b17e48039864
Create Date: 2026-04-17 10:32:04.405083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0642a7f8ed12'
down_revision = 'b17e48039864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_code', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
