"""update changes in Car and VehicleProfile

Revision ID: 1a56c84b07a6
Revises: 68c6eb818ea8
Create Date: 2026-06-26 15:14:10.640075

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1a56c84b07a6"
down_revision = "68c6eb818ea8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cars", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "vehicle_identity_source",
                sa.String(length=20),
                nullable=False,
                server_default="manual",
            )
        )

    with op.batch_alter_table("vehicle_profiles", schema=None) as batch_op:
        batch_op.drop_column("manufacturer")
        batch_op.drop_column("make")
        batch_op.drop_column("model")
        batch_op.drop_column("model_year")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vehicle_profiles", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("model_year", sa.VARCHAR(length=10), nullable=True)
        )
        batch_op.add_column(sa.Column("model", sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column("make", sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(
            sa.Column("manufacturer", sa.VARCHAR(length=100), nullable=True)
        )

    with op.batch_alter_table("cars", schema=None) as batch_op:
        batch_op.drop_column("vehicle_identity_source")

    # ### end Alembic commands ###
