"""update changes in VehicleDTC

Revision ID: 290c5c28dd7d
Revises: 1a56c84b07a6
Create Date: 2026-06-29 19:05:26.802849

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "290c5c28dd7d"
down_revision = "09d596bc12e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vehicle_dtcs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cleared_by", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_vehicle_dtcs_cleared_by_users", "users", ["cleared_by"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vehicle_dtcs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_vehicle_dtcs_cleared_by_users", type_="foreignkey")
        batch_op.drop_column("cleared_by")

    # ### end Alembic commands ###
