"""add changes to model

Revision ID: 42e597791db4
Revises: 76b4522c1283
Create Date: 2026-02-28 09:52:25.725711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42e597791db4'
down_revision = '76b4522c1283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_faults', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_car_faults_reviewed_by_users', 'users', ['reviewed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_faults', schema=None) as batch_op:
        batch_op.drop_constraint('fk_car_faults_reviewed_by_users', type_='foreignkey')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('reviewed_at')

    # ### end Alembic commands ###
