"""add alert workflow status in VehicleHealthAlert model

Revision ID: 45ebccb671a2
Revises: 026ea788d410
Create Date: 2026-05-31 09:21:03.194245

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "45ebccb671a2"
down_revision = "026ea788d410"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vehicle_health_alerts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column("acknowledged_at", sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column("acknowledged_by_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_alert_acknowledged_by", "users", ["acknowledged_by_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vehicle_health_alerts", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("acknowledged_by_id")
        batch_op.drop_column("acknowledged_at")
        batch_op.drop_column("status")

    # ### end Alembic commands ###
