"""update UserMemory

Revision ID: 4ea36e64289c
Revises: 78381ef889df
Create Date: 2026-04-02 10:50:58.469577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea36e64289c'
down_revision = '78381ef889df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_memory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_vehicle', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_topic', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_memory', schema=None) as batch_op:
        batch_op.drop_column('last_topic')
        batch_op.drop_column('last_vehicle')

    # ### end Alembic commands ###
