"""Check schema

Revision ID: 554e83093870
Revises: 52c8a16467c3
Create Date: 2026-06-25 11:57:59.185965

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "554e83093870"
down_revision = "52c8a16467c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("booking_intent", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("car_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.create_foreign_key(
            "fk_booking_intent_user", "users", ["user_id"], ["id"]
        )
        batch_op.create_foreign_key("fk_booking_intent_car", "cars", ["car_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("booking_intent", schema=None) as batch_op:
        batch_op.drop_constraint("fk_booking_intent_car", type_="foreignkey")
        batch_op.drop_constraint("fk_booking_intent_user", type_="foreignkey")
        batch_op.alter_column("car_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###
