"""add notes to consultation model

Revision ID: 63f0dddea696
Revises: 433f6c788bde
Create Date: 2026-02-27 12:43:58.378849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f0dddea696'
down_revision = '433f6c788bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
