"""Add manufacturer fields to VehicleProfile

Revision ID: 68c6eb818ea8
Revises: 554e83093870
Create Date: 2026-06-26 14:49:36.958225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c6eb818ea8'
down_revision = 'ea28d5290dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('make', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('model_year', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('engine_model', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_profiles', schema=None) as batch_op:
        batch_op.drop_column('engine_model')
        batch_op.drop_column('model_year')
        batch_op.drop_column('model')
        batch_op.drop_column('make')
        batch_op.drop_column('manufacturer')

    # ### end Alembic commands ###
