"""add car drivers to database

Revision ID: 73313b13c6a6
Revises: 036d7fd633b4
Create Date: 2026-04-15 12:17:46.970219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73313b13c6a6'
down_revision = '036d7fd633b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_drivers')
    # ### end Alembic commands ###
