"""add changes to consultation model

Revision ID: 76b4522c1283
Revises: 63f0dddea696
Create Date: 2026-02-27 21:26:43.427145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b4522c1283'
down_revision = '63f0dddea696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.alter_column('advisor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.alter_column('advisor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
