"""recreate conversation records

Revision ID: 7b089086bfe5
Revises: 97892f704afb
Create Date: 2026-05-11 16:49:26.773952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b089086bfe5'
down_revision = '97892f704afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('concern', sa.Text(), nullable=True),
    sa.Column('advisor_summary', sa.Text(), nullable=True),
    sa.Column('emotional_state', sa.String(length=50), nullable=True),
    sa.Column('urgency_level', sa.String(length=50), nullable=True),
    sa.Column('escalation_level', sa.String(length=50), nullable=True),
    sa.Column('recommended_action', sa.String(length=120), nullable=True),
    sa.Column('consultation_related', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_conversation_record_user_id'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['cars.id'], name='fk_conversation_record_vehicle_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_records')
    # ### end Alembic commands ###
