"""add driver daily checkins

Revision ID: 97892f704afb
Revises: 9ec4e4575a0c
Create Date: 2026-04-18 06:32:44.222389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97892f704afb'
down_revision = '9ec4e4575a0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('driver_score')

    # ### end Alembic commands ###
