"""add driver daily checkins

Revision ID: 9ec4e4575a0c
Revises: b2c74e6b1bfa
Create Date: 2026-04-18 06:06:35.342353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec4e4575a0c'
down_revision = 'b2c74e6b1bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('tyre_warning', sa.Boolean(), nullable=True),
    sa.Column('fuel_low', sa.Boolean(), nullable=True),
    sa.Column('dashboard_light', sa.Boolean(), nullable=True),
    sa.Column('vibration', sa.Boolean(), nullable=True),
    sa.Column('unusual_sound', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driver_checkins')
    # ### end Alembic commands ###
