"""allow nullable draft assessment fields

Revision ID: ac23b4434c19
Revises: 42e597791db4
Create Date: 2026-02-28 12:29:31.655667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac23b4434c19'
down_revision = '42e597791db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_assessments', schema=None) as batch_op:
        batch_op.alter_column('engine_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('transmission_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('suspension_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('electrical_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('cooling_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('professional_recommendation',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_assessments', schema=None) as batch_op:
        batch_op.alter_column('professional_recommendation',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('cooling_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('electrical_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('suspension_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('transmission_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('engine_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    # ### end Alembic commands ###
