"""modify access code

Revision ID: b2c74e6b1bfa
Revises: 0642a7f8ed12
Create Date: 2026-04-17 11:38:40.471794

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b2c74e6b1bfa"
down_revision = "0642a7f8ed12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("access_code", schema=None) as batch_op:
        batch_op.add_column(sa.Column("owner_id", sa.Integer(), nullable=True))
        batch_op.alter_column("expires_at", existing_type=sa.DATETIME(), nullable=False)
        batch_op.create_foreign_key(
            "fk_access_code_owner_id_users", "users", ["owner_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("access_code", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column("expires_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.drop_column("owner_id")

    # ### end Alembic commands ###
