"""add transmission_type to car model

Revision ID: b51dbc7679e9
Revises: ac23b4434c19
Create Date: 2026-03-10 19:45:19.709508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51dbc7679e9'
down_revision = 'ac23b4434c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transmission_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('transmission_type')

    # ### end Alembic commands ###
