"""add priority access to CarOwnership

Revision ID: ce2520ee6e50
Revises: 11c9da2fa431
Create Date: 2026-05-14 07:01:09.936730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce2520ee6e50'
down_revision = '11c9da2fa431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_ownership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority_access', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_ownership', schema=None) as batch_op:
        batch_op.drop_column('priority_access')

    # ### end Alembic commands ###
