from flask import Blueprint, jsonify
from flask_login import login_required, current_user

from models import Car, CarOwnership
from services.vehicle_intelligence import (
    calculate_vehicle_health,
    generate_rina_insight,
)

# Aura: intelligence as interpretation, not metrics
intelligence_bp = Blueprint("intelligence", __name__)


# =====================================================
# VEHICLE HEALTH STATUS (CLIENT VIEW)
# =====================================================


@intelligence_bp.route("/cars/<int:car_id>/health", methods=["GET"])
@login_required
def get_car_health(car_id):
    """
    Returns interpreted vehicle health status
    for the client.

    This is not a diagnosis.
    It is a professional health overview based on available data.
    """

    car = Car.query.get_or_404(car_id)

    ownership = CarOwnership.query.filter_by(
        car_id=car.id,
        user_id=current_user.id,
        is_active=True,
    ).first_or_404()

    health = calculate_vehicle_health(car, ownership)

    return (
        jsonify(
            {
                "car_id": car.id,
                "vehicle": f"{car.brand} {car.model} {car.year}",
                "current_mileage": car.current_mileage,
                # Aura language
                "health_status": health.get("health_status"),
                "health_label": health.get("label"),
                "overview": (
                    "This assessment reflects the vehicle’s current condition "
                    "based on recorded activity and reported observations."
                ),
                # Interpreted risks (not raw metrics)
                "active_risks": health.get("risk_reasons", []),
                # Advisor-led next step
                "recommended_next_step": health.get("next_action"),
                # Disclaimer
                "disclaimer": (
                    "This overview is informational and does not replace "
                    "a professional vehicle assessment by Ajebo Fix."
                ),
            }
        ),
        200,
    )


# =====================================================
# A.J. RINA — CLINICAL SUMMARY (USER-FACING)
# =====================================================


@intelligence_bp.route("/cars/<int:car_id>/rina/insight", methods=["GET"])
@login_required
def get_rina_insight(car_id):
    """
    Returns a calm, non-diagnostic narrative summary
    generated by A.J. Rina.

    Rina does not provide repairs or diagnoses.
    She assists in understanding the vehicle’s condition
    and guides clients toward professional consultation.
    """

    car = Car.query.get_or_404(car_id)

    ownership = CarOwnership.query.filter_by(
        car_id=car.id,
        user_id=current_user.id,
        is_active=True,
    ).first_or_404()

    insight = generate_rina_insight(car, ownership)

    return (
        jsonify(
            {
                "car_id": car.id,
                "vehicle": f"{car.brand} {car.model} {car.year}",
                # Aura framing
                "assistant": "A.J. Rina — Vehicle Health Assistant",
                "summary": insight,
                "guidance": (
                    "For clarity or next steps, an Ajebo Fix advisor "
                    "can review this vehicle through a private consultation."
                ),
                "disclaimer": (
                    "Rina’s summaries are informational only and do not "
                    "constitute mechanical diagnosis or repair instruction."
                ),
            }
        ),
        200,
    )
